pipeline {
    agent any
    tools {
        maven 'Maven-3.9'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
		dir('starter'){  
              sh 'mvn -B clean package'
            }}
        }
        stage('Test') {
            steps {
		dir('starter'){
                sh 'mvn -B test'
            }}
            post {
                always {
                    junit 'target/test-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
        	dir('starter'){      
	  	archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }}
        }
    }
}
